service: next-react-notes

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  next:
    handler: next.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-next.js

package:
  include:
    - .next/standalong           # 包含 Next.js 打包生成的文件
    # - serverless.js      # Lambda 函数入口文件

custom:
  serverless-next.js:
    basePath: /app  # 配置基础路径
    assetsBucketName: nextjs-app-assets
