import type { Metadata } from "next";
import "./globals.css";
import "./style.css";
import Sidebar from "@/components/SideBar/Sidebar";
import { locales } from "@/root/config";
import Footer from "@/components/Footer";

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {
    lng
  }
}: Readonly<{
  children: React.ReactNode;
  params: {
    lng: string
  }
}>) {

  return (
    <html lang={lng}>
      <body>
        <div className="container">
          <div className="main">
            <Sidebar lng={lng} />
            <section className="col note-viewer">{children}</section>
          </div>
          <Footer lng={lng} />
        </div>
      </body>
    </html>
  );
}
